spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
         hibernate:
           temp.use_jdbc_metadata_defaults: false
           dialect: org.hibernate.dialect.PostgreSQLDialect


  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: ada539!
    driverClassName: org.postgresql.Driver
server:
    port: 8602
    servlet:
      context-path: /student